name: 🍺 sync
    
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for listed branches
  push:
    branches: [main]
    
  workflow_dispatch:
  
# Cancel the current run if a new run is triggered
concurrency:
  group: CI-${{ github.ref }}-1
  cancel-in-progress: true 

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create \
        --title "merge changes into melbourne-time-zone" \
        --body "This pull request was automatically created by a GitHub Action to merge the latest changes from the main branch." \
        --base feature/melbourne-time-zone \
        --head main
