name: 🍺 sync
    
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for listed branches
  push:
    branches: [main]
    
  workflow_dispatch:
  
# Cancel the current run if a new run is triggered
concurrency:
  group: CI-${{ github.ref }}-1
  cancel-in-progress: true 

jobs:
  createPullRequest:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: feature/melbourne-time-zone


    - name: Merge Changes from Master to Melbourne Branch
      run: |
        git checkout -b Melbourne
        git push
        git pull
        git merge origin/main --allow-unrelated-histories --no-edit
    

    - name: Rebuild Melbourne Branch
      run: |
        git checkout Melbourne
        npm run all
        git add -A
        git commit -m "Rebuild Melbourne branch"
        git push origin Melbourne


    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
        --title "merge changes into melbourne-time-zone" \
        --body "This pull request was automatically created by a GitHub Action to merge the latest changes main branch" \
        --base feature/melbourne-time-zone \
        --head Melbourne
