name: 🍺 sync
    
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for listed branches
  push:
    branches: [main]
  
# Cancel the current run if a new run is triggered
concurrency:
  group: CI-${{ github.ref }}-1
  cancel-in-progress: true 

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3    
      - name: create pull request
        run: |
          git checkout -b syncFromMain
          git push --set-upstream origin syncFromMain
          gh pr create -B feature/melbourne-time-zone -H syncFromMain --title 'Merge main into melbourne-time-zone' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
